### Добавить вопрос/ответ
POST http://localhost:8080/exam/java/add?question=Question1&answer=Answer1

### Добавить вопрос/ответ
POST http://localhost:8080/exam/java/add?question=Question2&answer=Answer2

### Добавить вопрос/ответ
POST http://localhost:8080/exam/java/add?question=Question3&answer=Answer3

### Добавить вопрос/ответ
POST http://localhost:8080/exam/java/add?question=Question4&answer=Answer4

### Добавить вопрос/ответ
POST http://localhost:8080/exam/java/add?question=Question5&answer=Answer5

###Список всех попросов
GET http://localhost:8080/exam/java/getAll

###Получить рандомный вопрос
GET http://localhost:8080/exam/java/randomQuestion

###Удалить вопрос
DELETE http://localhost:8080/exam/java/remove
Content-Type: application/json

{
  "question": "Question1",
  "answer": "Answer1"
}

### Найти вопрос
GET http://localhost:8080/exam/java/find
Content-Type: application/json

{
"question": "Question1",
  "answer": "Answer1"
}

### Случайные вопросы
GET http://localhost:8080/exam/java/amount?amount=2

